routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Admin\UserController;
use Admin\ProductController;
use Admin\MenuController;
use Admin\SubMenuController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\TemplateController;
use App\Http\Controllers\Admin\SettingController;
use App\Http\Controllers\Admin\OrdersController;
use Admin\FontController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
})->name('index');


//Admin Routes
Route::prefix('admin')->middleware('auth')->group(function () {
    Route::group(['middleware' => 'role:Admin'], function() {
        Route::get('/dashboard', [DashboardController::class, 'index'])->name('admin.dashboard');
        Route::get('/templates', [TemplateController::class, 'index'])->name('admin.templates');
        Route::prefix('setting')->group(function () {
            Route::get('/', [SettingController::class, 'index'])->name('admin.setting.index');
            Route::resource('/users', UserController::class);
        });
        Route::get('/orders', [OrdersController::class, 'index'])->name('admin.order.index');
        // Route::prefix('orders')->group(function () {
        //     Route::get('/pending', [OrdersController::class, 'pendingOrder'])->name('admin.order.pending');
        //     // Route::get('/completed', [OrdersController::class, 'pendingOrder'])->name('admin.order.completed');
        //     // Route::get('/in-progress', [OrdersController::class, 'pendingOrder'])->name('admin.order.inprogress');
        // });
        Route::any('/designGenerator/',function() { 
            View::addExtension('html', 'php');
            return view('admin.templates.addTemplate'); 
        
        })->name('admin.newtemplate');

        Route::any('/designGenerator/#/edit/{id}',function() { 
            View::addExtension('html', 'php');
            return view('admin.templates.addTemplate'); 
        
        })->name('admin.edittemplate');
        Route::get('/products/{id}/edit/{imageId}/remove', [App\Http\Controllers\Admin\ProductController::class, 'softDeleteProductImages'])->name('admin.product.image.delete');
        Route::put('/products/{id}/edit/{sizeId}/update', [App\Http\Controllers\Admin\ProductController::class, 'updateProductSizeQty'])->name('admin.product.size.update');
        Route::get('/products/{id}/edit/{sizeId}/delete', [App\Http\Controllers\Admin\ProductController::class, 'deleteProductSizeQty'])->name('admin.product.size.delete');
        Route::resource('products', ProductController::class);
        Route::resource('menus', MenuController::class);
        Route::resource('submenus', SubMenuController::class);
        Route::resource('font', FontController::class);
        Route::get('/orders/payment/view/{referenceId}', [OrdersController::class, 'viewPaymentDetails'])->name('admin.order.payment');
    });
});

app/Models/Menu.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Menu extends Model
{
    use HasFactory;

    protected $fillable = ['title', 'link', 'status', 'orderBy'];

    // public function submenus() {

    //     return $this->hasMany('App\Models\SubMenuItem', 'parent_id', 'id');
    // }
    // public function parent() {

    //     return $this->hasOne('App\Models\Menu', 'id', 'parent_id');
    
    // }
    
    // public function children() {
    
    // return $this->hasMany('App\Models\Menu', 'parent_id', 'id');
    
    // }
    
    // public static function tree() {
    
    // return static::with(implode('.', array_fill(0, 100, 'children')))->where('parent_id', '=', '0')->get();
    
    // }

    public function submenus() {

        return $this->hasMany('App\Models\SubMenuItem', 'parent_id', 'id')->where('status', 'ENABLED');

    }

}

app/Http/Controllers/Admin/MenuController.php
<?php
namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Menu;
use Illuminate\Http\Request;

class MenuController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // //
        // $menus = Menu::where('parent_id', '=', 0)->get();
        // $allMenus = Menu::pluck('title','id')->all();
        // return view('menu.menuTreeview',compact('menus','allMenus'));
        // $menus = Menu::with('submenus')->orderBy('orderBy', 'asc')->get();
        // Menu::with('submenus')->orderBy('orderBy')->get();
        // $menu = new \App\Models\Menu;
        // $menuItems = $menu->tree();
        // $products = Product::with('category')->paginate(20);
        // dd($menuItems);


        $menuItems = Menu::with('submenus')->orderBy('orderBy')->get();


        return view('admin.menus.index', ['menus'  => $menuItems, 'menuCount' => 6]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('admin.menus.create', ['menus' => Menu::get()]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        // str_replace(' ','_',$file);
        // strtolower
        // $request->request->add(['parent_id' => 0]); //add request
        $request->offsetSet('title', strtoupper($request->title));
        $request->request->add(['link' => 'products/' . str_replace(' ','_',strtolower($request->title))]); //add request
        $request->request->add(['orderBy' => '7']); //add request
        Menu::create($request->all());
        return redirect()->route('menus.index')
            ->with('success','Menu created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Menu  $menu
     * @return \Illuminate\Http\Response
     */
    public function show(Menu $menu)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Menu  $menu
     * @return \Illuminate\Http\Response
     */
    public function edit(Menu $menu)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Menu  $menu
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Menu $menu)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Menu  $menu
     * @return \Illuminate\Http\Response
     */
    public function destroy(Menu $menu)
    {
        //
    }



    // SubMenus Controller

    public function submenuCreate()
    {
        //
        return view('admin.menus.submenu.create');
    }
}

resources/views/admin/menus/create.blade.php
@extends('templates.main')

@section('content')
<div class="container">
    <h1>Create New Menu</h1>
    <div class="card" style="padding:10px">
        <form method="post" action="{{ route('menus.store') }}">
            @csrf
            <div class="mb-3">
                <label for="title" class="form-label">Menu Title</label>
                <input name="title" type="text" class="form-control @error('title') is-invalid  @enderror" id="title"
                    aria-describedby="title" value="{{ old('title') }}">
                @error('title')
                <span class="invalid-feedback" role="alert">
                    {{ $message }}
                </span>
                @enderror
            </div>

            <div class="mb-3">
                <label class="form-label" for="parent_id">
                    Insert After
                </label>
                <select name="orderBy" class="form-select" id="parent_id">
                    @foreach($menus as $menu)
                        <option value={{ $menu->id }}>{{$menu->title}}</option>
                    @endforeach
                </select>
            </div>

            {{-- <div class="mb-3">
                <label for="link" class="form-label">Link</label>
                <input name="link" type="text" value="{{ 'products/' }}" class="form-control @error('link') is-invalid  @enderror" id="link"
                    aria-describedby="link" value="{{ old('link') }}">
                @error('link')
                <span class="invalid-feedback" role="alert">
                    {{ $message }}
                </span>
                @enderror
            </div> --}}

            {{-- <div class="mb-3">
                <label class="form-label" for="category_id">
                    Category
                </label>
                <select name="category_id" class="form-select" id="category_id">
                    @foreach($categories as $category)
                        <option value={{ $category->id }}>{{$category->category_title}}</option>
                    @endforeach
                </select>
            </div> --}}

            <div class="mb-3">
                <label class="form-label" for="status">
                    Status
                </label>
                <select name="status" class="form-select">
                    <option value="ENABLED" selected>ENABLED</option>
                    <option value="DISABLED">DISABLED</option>
                </select>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>
@endsection

resources/views/admin/menus/index.blade.php
@extends('templates.main')
@section('content')
<style>
    /* th, td {
          border: 1px solid black;
    } */
    th, td {
        padding: 15px;
    }
</style>
<div class="container">
    <div class="row">
        <div class="col-12">
            <h1 class="float-start">Menus</h1>
            <a class="btn btn-sm btn-outline-success float-end" href="{{ route('submenus.create') }}"
                role="button">Create Sub Menu</a>
            {{-- @if ($menuCount < 6) --}}
            <a class="btn btn-sm btn-outline-success float-end" href="{{ route('menus.create') }}" role="button"
                style="margin-right:10px;">Create Menu</a>
            {{-- @endif --}}
        </div>
    </div>
    @if ($message = Session::get('success'))
    <div class="alert alert-success">
        <p>{{ $message }}</p>
    </div>
    @endif
    <div class="card">
        <table class="table">
            <thead>
                {{-- <th>#</th> --}}
                <td class="text-center">MENU NAME</td>
            </thead>
            <tbody>
                @foreach ($menus as $item)
                <tr>
                    {{-- <th>#</th> --}}
                    <td>
                        <label class="text-capitalize fw-bold">{{ $item->title }}</label>&nbsp;
                        @if ($item->status == 'ENABLED')
                        <span class="badge  bg-success">{{ $item->status }}</span>
                        @else
                        <span class="badge  bg-danger">{{ $item->status }}</span>
                        @endif
                        <table style="width:100%;margin-top:10px;margin-bottom: 10px;" class="table">
                            <tbody>
                                @foreach($item->submenus as $submenu)
                                <tr>
                                    <td style="width: 50px;">&nbsp;</td>
                                    <td> ->
                                        <label>{{ $submenu->title }}</label> &nbsp;
                                        @if ($submenu->status == 'ENABLED')
                                        <span class="badge  bg-success">{{ $submenu->status }}</span>
                                        @else
                                        <span class="badge  bg-danger">{{ $submenu->status }}</span>
                                        @endif
                                        {{-- @if (count($submenu->children) > 0)
                                        <table style="width:100%;margin-top:10px;margin-bottom: 10px;" class="table">
                                            <tbody>
                                                @foreach($submenu->children as $submenu1)
                                                <tr>
                                                    <td style="width: 50px;">&nbsp;</td>
                                                    <td>
                                                        -> <label>{{ $submenu1->title }}</label>&nbsp;
                                                        @if ($submenu1->status == 'ENABLED')
                                                        <span class="badge  bg-success">{{ $submenu1->status }}</span>
                                                        @else
                                                        <span class="badge  bg-danger">{{ $submenu1->status }}</span>
                                                        @endif
                                                    </td>
                                                    {{-- <td> --}}
                                                    {{-- /toggling enabled and disabled --}}
                                                    {{-- <div class="form-check form-switch">
                                                            <input class="form-check-input" type="checkbox" id="flexSwitchCheckChecked" checked>
                                                        </div> --}}
                                                    {{-- </td> --}}
                                                {{-- </tr>
                                                @endforeach
                                            </tbody>
                                        </table>
                                        @endif --}}
                                    {{-- <td style="width:100px"> --}}
                                    </td>
                                    {{-- <td> --}}
                                    {{-- /toggling enabled and disabled --}}
                                    {{-- <div class="form-check form-switch">
                                            <input class="form-check-input" type="checkbox" id="flexSwitchCheckChecked" checked>
                                        </div> --}}
                                    {{-- </td> --}}
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </td>
                    @endforeach
                </tr>
            </tbody>
        </table>
    </div>
</div>

@endsection