routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Admin\UserController;
use Admin\ProductController;
use Admin\MenuController;
use Admin\SubMenuController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\TemplateController;
use App\Http\Controllers\Admin\SettingController;
use App\Http\Controllers\Admin\OrdersController;
use Admin\FontController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
})->name('index');


//Admin Routes
Route::prefix('admin')->middleware('auth')->group(function () {
    Route::group(['middleware' => 'role:Admin'], function() {
        Route::get('/dashboard', [DashboardController::class, 'index'])->name('admin.dashboard');
        Route::get('/templates', [TemplateController::class, 'index'])->name('admin.templates');
        Route::prefix('setting')->group(function () {
            Route::get('/', [SettingController::class, 'index'])->name('admin.setting.index');
            Route::resource('/users', UserController::class);
        });
        Route::get('/orders', [OrdersController::class, 'index'])->name('admin.order.index');
        // Route::prefix('orders')->group(function () {
        //     Route::get('/pending', [OrdersController::class, 'pendingOrder'])->name('admin.order.pending');
        //     // Route::get('/completed', [OrdersController::class, 'pendingOrder'])->name('admin.order.completed');
        //     // Route::get('/in-progress', [OrdersController::class, 'pendingOrder'])->name('admin.order.inprogress');
        // });
        Route::any('/designGenerator/',function() { 
            View::addExtension('html', 'php');
            return view('admin.templates.addTemplate'); 
        
        })->name('admin.newtemplate');

        Route::any('/designGenerator/#/edit/{id}',function() { 
            View::addExtension('html', 'php');
            return view('admin.templates.addTemplate'); 
        
        })->name('admin.edittemplate');
        Route::get('/products/{id}/edit/{imageId}/remove', [App\Http\Controllers\Admin\ProductController::class, 'softDeleteProductImages'])->name('admin.product.image.delete');
        Route::put('/products/{id}/edit/{sizeId}/update', [App\Http\Controllers\Admin\ProductController::class, 'updateProductSizeQty'])->name('admin.product.size.update');
        Route::get('/products/{id}/edit/{sizeId}/delete', [App\Http\Controllers\Admin\ProductController::class, 'deleteProductSizeQty'])->name('admin.product.size.delete');
        Route::resource('products', ProductController::class);
        Route::resource('menus', MenuController::class);
        Route::resource('submenus', SubMenuController::class);
        Route::resource('font', FontController::class);
        Route::get('/orders/payment/view/{referenceId}', [OrdersController::class, 'viewPaymentDetails'])->name('admin.order.payment');
    });
});

app/Http/Controllers/Admin/OrdersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class OrdersController extends Controller
{
    //

    public function index() {
        $orders = array();
        $orders_1 = DB::table('order')->get();
        foreach (json_decode($orders_1, true) as $key => $value1) {
            $productId = $value1['product_id'];
            $referenceID = $value1['payment_reference_id'];
            $productDetails = DB::table('products')->where('id', $productId)->first();
            $categoryId = $productDetails->category_id;
            $categoryDetails = DB::table('category')->where('id', $categoryId)->first();
            $paymentDetails = DB::table('payment')->where('payment_link_reference_id', $referenceID)->first();
            $templateData = DB::table('design_templates')->where('id', $value1['design_id'])->first();
            // dd($templateData);
            $userId = $value1['user_id'];
            if ( !empty($userId) ) {
                $userDetails = DB::table('users')->where('id', $userId)->first();
                $data['user_name'] = $userDetails ? $userDetails->name: '';
                $data['user_email'] = $userDetails ? $userDetails->email : '';
            } else {
                $data['user_name'] = 'Guest';
                $data['user_email'] = 'Guest';
            }
            $data['id'] = $value1['id'];
            $data['category_name'] = $categoryDetails->category_title;
            $data['product_name'] = $productDetails->product_name;
            $data['design_id'] = $value1['design_id'];
            $templateData && $templateData->fill_template1 ? $data['design_template'] = $templateData->fill_template1: $data['design_template'] = '';
            $data['status'] = $value1['status'];
            $data['order_date'] = $value1['created_at'];
            $data['quantity'] = $value1['quantity'];
            $data['paymentReferenceID'] = $referenceID;
            $data['paymentDetails']= $paymentDetails;
            // dd($orders);
            // return view('admin.orders.index', ['orders' => $orders]);
            $data['price'] = $value1['price'];
            $data['variable_date'] = $value1['variable_data'];
            array_push($orders, $data);
        }
        return view('admin.orders.index', ['orders' => $orders]);
    }

    public function viewPaymentDetails() {
        
    }
}

resources/views/admin/orders/index.blade.php
@extends('templates.main')
@section('content')
<style>
     /* th, td {
          border: 1px solid black;
    }
    th, td {
        padding: 15px;
    } */
</style>
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <h1 class="float-start">Orders</h1>
            {{-- <a class="btn btn-sm btn-success float-end" href="{{ route('users.create') }}" role="button">Create</a>  --}}
        </div>
    </div>
    <div class="card p-2">
        <table class="table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>User Name</th>
                    <th>User Email</th>
                    <th>Category Name</th>
                    <th>Product Name</th>
                    <th class="text-center">Design Selected</th>
                    <th class="text-center">Status</th>
                    <th class="text-center">Actions</th>
                    <th class="text-center">Payment Reference ID</th>
                    <th class="text-center">Payment status</th>
                    <th class="text-center">Payment Date</th>
                    <th class="text-center">Payment Amount</th>
                </tr>
            </thead>
            <tbody>
                @foreach($orders as $key => $order)
                <tr>
                    <th scope="row">{{ $key + 1 }}</th>
                    <td>{{ $order['user_name'] }}</td>
                    <td>{{ $order['user_email'] }}</td>
                    <td>{{ $order['category_name'] }}</td>
                    <td>{{ $order['product_name'] }}</td>
                   
                    <td class="text-center">
                        @if (!empty($order['design_id']))
                            <img src="{{ $order['design_template'] }}" style="width: 200px;height: auto" />
                        @endif
                    </td>
                    <td class="text-center">
                        @if ($order['status'] == 0) <span class="badge bg-danger">Pending</span>
                        @elseif ($order['status'] == 1) <span class="badge bg-primary">In Progress</span>
                        @elseif ($order['status'] == 2) <span class="badge bg-success">Completed</span>
                        @endif
                    </td> 
                    <td class="text-center">
                        {{-- <a class="btn btn-sm btn-primary" href="{{ route('users.edit', $user->id) }}" role="button">Edit</a> --}}
                        @if ($order['status'] == 0) 
                            {{-- <form id="delete-user-form-{{$user['id']}}" action="{{route('users.destroy', $user->id )}}" method="POST" style="display:none;">
                            @csrf
                            @method("DELETE")
                            </form> --}}
                            <a class="btn btn-sm btn-primary" href="#" role="button">Start Order</a>
                        @elseif ($order['status'] == 1) 
                            <a class="btn btn-sm btn-success" href="#" role="button">Finish Order</a>
                        @endif
                       {{-- <button type="button" class="btn btn-sm btn-danger" onclick="event.preventDefault();document.getElementById('delete-user-form-{{$user->id}}').submit();">
                            Delete
                        </button> --}}
                        {{-- <form id="delete-user-form-{{$user['id']}}" action="{{route('users.destroy', $user->id )}}" method="POST" style="display:none;">
                        @csrf
                        @method("DELETE")
                        </form> --}}
                    </td>
                    <td >
                        @if (!empty($order['paymentReferenceID']))
                        {{ $order['paymentReferenceID'] }}
                    @else
                        ----
                    @endif
                    </td>
                    <td class="text-center" style="text-transform: uppercase;">
                        @if (!empty($order['paymentDetails']->payment_link_status))
                            {{ $order['paymentDetails']->payment_link_status }}
                        @else
                            Pending
                        @endif
                    </td>
                    <td class="text-center">
                        @if (!empty($order['paymentDetails']->updated_at))
                            {{ $order['paymentDetails']->updated_at }}
                        @else
                            -----
                        @endif
                    </td>
                    <td class="text-center">
                        @if (!empty($order['paymentDetails']->amount))
                            Rs. {{ $order['paymentDetails']->amount }}
                        @else
                            -----
                        @endif
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
        {{-- {{ $orders->links() }} --}}
    </div>
</div>
{{-- <script>
    $(function() {
      $('.toggle-class').change(function() {
          var status = $(this).prop('checked') == true ? 1 : 0; 
          var user_id = $(this).data('id'); 
           
          $.ajax({
              type: "GET",
              dataType: "json",
              url: '/changeStatus',
              data: {'status': status, 'user_id': user_id},
              success: function(data){
                console.log(data.success)
              }
          });
      })
    })
  </script> --}}
@endsection